<?php 
require 'config/db_connect.php'; 

if(!isset($_SESSION['user_id'])) {
    header("Location: index.php");
    exit();
}

if ($_SESSION['role'] !== 'Admin') {
    header("Location: dashboard.php");
    exit();
}

$query = "
    SELECT a.*, u.full_name, u.role 
    FROM audit_logs a 
    LEFT JOIN users u ON a.user_id = u.user_id 
    ORDER BY a.timestamp DESC 
    LIMIT 2000"; 
$logs = $conn->query($query);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <title>System Audit Trail - Fixie DRMS</title>
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
   
</head>
<body>

    <?php include 'sidebar.php'; ?>

    <div class="main-content fade-in">
        
        <div class="print-only-header">
            <div>
                <h1 class="print-header-brand">Fixie Computer Ventures</h1>
                <div class="print-header-sub">
                    <strong>System Security & Tracking Module</strong><br>
                    123 Technology Avenue, Tech Hub City, Philippines 1000<br>
                    Phone: (02) 8123-4567 | Email: admin@fixie.com
                </div>
            </div>
            <div class="text-end">
                <div class="print-title-doc">System Audit Trail</div>
                <div style="font-size: 9.5pt; margin-top: 8px; color: #495057;">
                    <strong>Date Generated:</strong> <?php echo date('F d, Y h:i A'); ?><br>
                    <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name'] ?? 'System Admin'); ?>
                </div>
            </div>
        </div>

        <div class="mb-4 d-flex justify-content-between align-items-center no-print-header">
            <div>
                <h2 class="fw-bold mb-1"><i class="fas fa-history text-primary me-2"></i> System Audit Trail</h2>
                <p class="text-muted mb-0">Security & Tracking Module: Highly detailed log of system activities and navigation.</p>
            </div>
            <button class="btn btn-primary shadow-sm fw-bold px-4" onclick="logAndPrint('System Audit Trail Report')">
                <i class="fas fa-print me-2"></i> Print Log Report
            </button>
        </div>

        <div class="card border-0 shadow-sm p-4 bg-white rounded-3">
            <div class="table-responsive">
                <table id="auditTable" class="table table-hover align-middle" style="width:100%;">
                    <thead class="bg-primary text-white text-uppercase small">
                        <tr>
                            <th>Timestamp</th>
                            <th>User & Role</th>
                            <th>Action Category</th>
                            <th>System Description</th>
                            <th>IP Address</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($logs && $logs->num_rows > 0): ?>
                            <?php while($row = $logs->fetch_assoc()): ?>
                            <tr>
                                <td class="ps-3 text-nowrap" data-sort="<?php echo strtotime($row['timestamp']); ?>">
                                    <div class="fw-bold text-dark"><?php echo date('M d, Y', strtotime($row['timestamp'])); ?></div>
                                    <small class="text-muted"><?php echo date('h:i:s A', strtotime($row['timestamp'])); ?></small>
                                </td>
                                <td>
                                    <span class="fw-bold d-block text-dark"><?php echo htmlspecialchars($row['full_name'] ?? 'System Process'); ?></span>
                                    <span class="badge bg-light text-secondary border"><?php echo htmlspecialchars($row['role'] ?? 'Automated'); ?></span>
                                </td>
                                <td>
                                    <?php 
                                        $action = strtoupper(htmlspecialchars($row['action_type'] ?? 'UNKNOWN')); 
                                        $badge = 'bg-secondary';
                                        
                                        // Specific UI badge colors for the highly detailed logs
                                        if($action === 'PAGE_VIEW') $badge = 'bg-light text-secondary border';
                                        elseif($action === 'VIEW_RECORD') $badge = 'bg-info bg-opacity-10 text-info border border-info';
                                        elseif($action === 'SEARCH') $badge = 'bg-dark text-white';
                                        elseif(strpos($action, 'LOGIN') !== false || strpos($action, 'SUCCESS') !== false) $badge = 'bg-success';
                                        elseif(strpos($action, 'UPLOAD') !== false || strpos($action, 'CREATE') !== false) $badge = 'bg-primary';
                                        elseif(strpos($action, 'UPDATE') !== false || strpos($action, 'EDIT') !== false || strpos($action, 'WORKFLOW') !== false) $badge = 'bg-info text-dark';
                                        elseif(strpos($action, 'ARCHIVE') !== false) $badge = 'bg-warning text-dark';
                                        elseif(strpos($action, 'RESTORE') !== false) $badge = 'bg-success';
                                        elseif(strpos($action, 'DELETE') !== false || strpos($action, 'ERROR') !== false || strpos($action, 'FAIL') !== false || strpos($action, 'PRINT') !== false) $badge = 'bg-danger';
                                    ?>
                                    <span class="badge <?php echo $badge; ?> px-2 py-1 shadow-sm"><?php echo $action; ?></span>
                                </td>
                                <td class="log-desc text-wrap" style="max-width: 300px;">
                                    <?php echo htmlspecialchars($row['description'] ?? ''); ?>
                                </td>
                                <td class="text-end pe-3 font-monospace text-muted small">
                                    <?php echo htmlspecialchars($row['ip_address'] ?? 'Unknown'); ?>
                                </td>
                            </tr>
                            <?php endwhile; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
        </div>
        
        <div class="print-footer">
            CONFIDENTIAL: This System Audit Trail is generated securely from Fixie DRMS. For internal administrative use only.
        </div>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#auditTable').DataTable({
                "order": [[ 0, "desc" ]],
                "pageLength": 25,
                "language": {
                    "search": "Search Logs:"
                }
            });
        });

        function logAndPrint(documentName) {
            fetch('api/log_print.php', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
                body: 'action=log_print&doc_name=' + encodeURIComponent(documentName)
            })
            .then(response => response.json())
            .then(data => {
                window.print(); 
                setTimeout(() => location.reload(), 1500);
            })
            .catch(error => {
                console.error('Error logging print:', error);
                window.print(); 
            });
        }
    </script>
</body>
</html>