<?php

declare(strict_types=1);

require_once __DIR__ . '/../config/db_connect.php';

header('Content-Type: application/json; charset=UTF-8');
header('Cache-Control: no-store, max-age=0');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    echo json_encode([
        'status' => 'error',
        'message' => 'Method not allowed.',
    ]);
    exit;
}

if (empty($_SESSION['user_id'])) {
    http_response_code(401);
    echo json_encode([
        'status' => 'error',
        'message' => 'Authentication is required.',
    ]);
    exit;
}

// Client-authored audit entries are intentionally disabled. Meaningful audit
// events must be generated by the server action that actually performs them.
http_response_code(410);
echo json_encode([
    'status' => 'error',
    'message' => 'This legacy audit endpoint is no longer available.',
]);
